# -*- coding: utf-8 -*-
"""AIML_OPTIMIZEDevenMORE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DK8IcSnQf-s3zurkfjIg1FIO4cTyt29
"""

!pip uninstall -y langchain langchain-core langchain-community
!pip install llama-index llama-index-llms-perplexity
!pip install pypdf sentence-transformers
!pip install llama-index-readers-file
!pip install llama-index llama-index-llms-perplexity
!pip install llama-index-readers-file
!pip install pypdf sentence-transformers chromadb

from llama_index.core import SimpleDirectoryReader
from llama_index.readers.file import CSVReader, PDFReader

from llama_index.llms.perplexity import Perplexity
from llama_index.core import VectorStoreIndex
!pip install -U llama-index

pip install llama-index-embeddings-huggingface llama-index-llms-perplexity

import os
import time
import glob

from llama_index.core import Document, Settings, VectorStoreIndex
from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.prompts import PromptTemplate
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.response_synthesizers import get_response_synthesizer


from llama_index.embeddings.huggingface import HuggingFaceEmbedding

embed_model = HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2")

print("All LlamaIndex modules imported successfully for version 0.14.6!")

CHUNKING_FILES = [
    "/content/Final 2024 BTech Syllabus book.pdf",
    "/content/Student Handbook.pdf",
]
print(len(CHUNKING_FILES))
NO_CHUNKING_FILES = [
    "/content/BTech_3rd_Sem_Timetable.csv",
    "/content/BTech_Majors.csv",
    "/content/Courses.csv",
    "/content/faculty.csv",
    "/content/3rd_sem_minors.csv",
    "/content/Holidays1.csv",
    "/content/3rd & 5th University Elective - All Schools.csv",
    "/content/MinorCourse.csv",
    "/content/sdi_timetable.csv",
    "/content/SOCSE_subjects.csv"
]
print(len(NO_CHUNKING_FILES))
HEADERS = {
    # Timetable: Who teaches what, where, and when.
    "BTech_3rd_Sem_Timetable.csv": "Section,Day,Time,Subject,Subject Faculty,Room No,Class Teacher",

    # Majors: Details about the B.Tech Majors offered.
    "BTech_Majors.csv": "Major,Faculty Lead,Semester 3 Courses,Semester 4 Courses,Semester 5 Courses,Semester 6 Courses,Semester 7 Courses,Total Credits,Career Roles,Description,Keywords",

    # Courses: Program, specialization, and fees data.
    "Courses.csv": "School,Program Type,Course/Specialization,Annual Tuition Fee (INR)",

    # Faculty: General faculty information.
    "faculty.csv": "Professor,Role,Qualification,School",

    # 3rd Sem Minors: Minor course time/faculty details.
    "3rd_sem_minors.csv": "SI NO,Minor Stream,Course Code,Course Name,Day,Time,Faculty,Room No",

    # Holidays: Official holiday list.
    "Holidays1.csv": "Holiday Type,Date,Days,Holiday Name",

    # University Electives: List of electives.
    "3rd & 5th University Elective - All Schools.csv": "SCHOOL,ELECTIVE,FACULTY,DAY,TIME,CLASSROOM",

    # Minor Course Details: Eligibility and seat capacity for minors.
    "MinorCourse.csv": "S No.,Offering School,Minor Stream,Eligibility Criteria,Number of Seats",

    "sdi_timetable.csv": "Week,Date,Day,Start Time, End Time, School",

    "SOCSE_subjects.csv":"School,Course,Semester,Subjects"
}

# Model and Storage Settings
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
PERSIST_DIRECTORY = './rvu_knowledge_base_llamaindex'
LLM_MODEL = "sonar-pro"

# LLM API Key Configuration
os.environ["PPLX_API_KEY"] = "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"
print(f"Perplexity API Key configured.")
print(f"Total files to process: {len(CHUNKING_FILES) + len(NO_CHUNKING_FILES)}")

from typing import List
from pathlib import Path

def load_data_and_create_nodes() -> List[Document]:
    """Loads files, handles chunking vs. no-chunking, and returns a list of LlamaIndex Documents."""
    all_documents = []
    splitter = SentenceSplitter(chunk_size=700, chunk_overlap=100)

# chunking
    print("\n--- Processing large, narrative files (with chunking)...")
    for file_path in CHUNKING_FILES:
        try:
            docs = PDFReader().load_data(Path(file_path))
            nodes = splitter.get_nodes_from_documents(docs)
            all_documents.extend(nodes)
            print(f"   -> Chunked {os.path.basename(file_path)} into {len(nodes)} pieces.")
        except Exception as e:
            print(f"ERROR processing {os.path.basename(file_path)}: {e}")
            print("   -> Skipping this file. Please check if the PDF is corrupted or password-protected.")

# no chunking
    print("\n--- Processing structured/tabular files (loaded whole/per row)...")
    for file_path in NO_CHUNKING_FILES:
        try:
            file_name = os.path.basename(file_path)
            file_extension = os.path.splitext(file_path)[1].lower()
            docs = []

            if file_extension == ".pdf":
                docs = PDFReader().load_data(Path(file_path))
            elif file_extension == ".csv":
                docs = CSVReader(concat_rows=False).load_data(Path(file_path))

                if file_name in HEADERS:
                    header = HEADERS[file_name]
                    contextual_docs = []
                    for doc in docs:
                        new_text = f"DATA CONTEXT: {header}\nDATA ROW: {doc.text}"
                        new_doc = Document(
                            text=new_text,
                            metadata=doc.metadata,
                            excluded_llm_metadata_keys=doc.excluded_llm_metadata_keys
                        )
                        contextual_docs.append(new_doc)
                    docs = contextual_docs

            all_documents.extend(docs)
            print(f"   -> Loaded {file_name} as {len(docs)} contextual row-units.")
        except Exception as e:
            print(f"ERROR processing {os.path.basename(file_path)}: {e}")
            print("   -> Skipping this file.")

    return all_documents

final_nodes = load_data_and_create_nodes()

if not final_nodes:
    print("\nCRITICAL: No data was processed. Cannot proceed with indexing.")
else:
    print(f"\nTotal FINAL nodes/chunks created for indexing: {len(final_nodes)}")

missing = [f for f in NO_CHUNKING_FILES if not os.path.exists(f)]
print("Missing files:", missing)

if final_nodes:
    print("\nIndexing Data with HuggingFace Embeddings ---")

    Settings.embed_model = HuggingFaceEmbedding(model_name=EMBEDDING_MODEL_NAME)

    start_time = time.time()
    vectorstore_index = VectorStoreIndex(nodes=final_nodes)
    end_time = time.time()

    print(f"Indexing complete! Time taken: {end_time - start_time:.2f} seconds.")

    retriever = VectorIndexRetriever(index=vectorstore_index, similarity_top_k=15)
    print("Retriever configured (k=15).")

pyq_papers = [
    {"subject": "Calculus", "aliases": ["calc", "math", "maths"], "link": "https://drive.google.com/file/d/1tXrqcjHtOpRTXJ8VzZspz8koZgHY_v--/view?usp=drive_link"},
    {"subject": "DAA", "aliases": ["design and analysis of algorithms", "algorithms"], "link": "https://drive.google.com/file/d/1mx1Etf03xz3nL_yUw7YommXgAwsh1vxf/view?usp=drive_link"},
    {"subject": "Computer Networks", "aliases": ["cn", "computer network"], "link": "https://drive.google.com/file/d/1rsTjO-k1WLu_ERdWEvobkAvh__3RT4u4/view?usp=drive_link"},
    {"subject": "Operating Systems", "aliases": ["os", "operating system"], "link": "https://drive.google.com/file/d/1TYewZtt1Ljw7uQRX53wpNOcHZpYOev1P/view?usp=drive_link"},
    {"subject": "Web Fundamentals and UX Design", "aliases": ["web", "web fundamentals"], "link": "https://drive.google.com/file/d/1G6XWn4T0NeiTkw8n1M1CUlsPqGffQmYx/view?usp=drive_link"},
    {"subject": "Linear Algebra", "aliases": [], "link": "https://drive.google.com/file/d/1FQAPGz1FHKabA0cKOYrdKQP5fUqqE_i2/view?usp=drive_link"},
    {"subject": "Programming in C", "aliases": ["pc", "c programming"], "link": "https://drive.google.com/file/d/198N9skc2ZlKLZEPNO0OGpN5TGtI0j2gM/view?usp=drive_link"},
    {"subject": "Exploring Science", "aliases": ["es"], "link": "https://drive.google.com/file/d/1oBLXiottjr65gCVt4dwhnOG5FcJbf1h7/view?usp=drive_link"},
    {"subject": "Engineering Explorations (EEX)", "aliases": ["eex", "engineering exploration"], "link": "https://drive.google.com/file/d/1wd7dshlapgp2ha3WXWzC0wWTlZXCpjbh/view?usp=drive_link"},
    {"subject": "Data Structures", "aliases": ["ds"], "link": "https://drive.google.com/file/d/1jrfjKFrBuQNi-QvVvyjsNsoXR7nJL65t/view?usp=drive_link"}
]

import re

def find_pyq_link(user_input):

    cleaned_input = re.sub(r'[^a-z0-9\s]', '', user_input.lower())

    paper_keywords = ["pyq", "previous year", "question paper", "paper", "past paper"]
    has_paper_keyword = any(word in cleaned_input for word in paper_keywords)

    if not has_paper_keyword:
        return None

    for paper in pyq_papers:
        terms_to_check = [paper["subject"].lower()] + [alias.lower() for alias in paper.get("aliases", [])]
        for term in terms_to_check:
            cleaned_term = re.sub(r'[^a-z0-9\s]', '', term)
            if cleaned_term and cleaned_term in cleaned_input:
                return f"📘 Here’s the previous year paper for {paper['subject']}:\n🔗 {paper['link']}"

    return None


def list_pyq_subjects():
    subject_list = "\n".join([
        f"- {paper['subject']} (Aliases: {', '.join(paper['aliases']) or 'None'})"
        for paper in pyq_papers
    ])
    return f"📚 Available PYQ Subjects: \n{subject_list}"

print("Query Engine and LLM Setup ---")

llm = Perplexity(model=LLM_MODEL, temperature=0.0)
Settings.llm = llm
print(f"LLM initialized using Perplexity model: {llm.model}")

template_str = """
You are the Smart Campus Assistant for RVU. Your job is to answer student and faculty questions
based only on the provided context, which is the RVU policy, majors, minors, courses, previous year question papers, faculty, fees structure and schedule documentation.

If the context does not contain the answer, you MUST state clearly:
"I apologize, but I cannot find that specific information in the provided RVU documents."
Do not use any prior knowledge or search the internet.

RV University is not Rocky Vista University. Any information asked regarding RVU should not linked to Rocky Vista University.

Context: {context}
Question: {query_str}
Answer:
"""
RAG_PROMPT_TEMPLATE = PromptTemplate(template_str)

response_synthesizer = get_response_synthesizer(
    llm=llm,
    text_qa_template=RAG_PROMPT_TEMPLATE,
    streaming=False
)

global qa_engine
qa_engine = RetrieverQueryEngine(
    retriever=retriever,
    response_synthesizer=response_synthesizer
)
print("LlamaIndex Query Engine established.")

!pip install flask flask-ngrok pyngrok

!pip install flask flask-ngrok llama-index==0.14.6

from pyngrok import ngrok
ngrok.set_auth_token("34hQQxA4XJaZeuB26ggLKWtqQTD_6JaWAoDjdbBGHNZ5HkShW")

try:
    print(type(qa_engine))
    print("qa_engine is ready!")
except NameError:
    print("qa_engine not defined yet! Please define or import it first.")

!kill -9 $(lsof -t -i:5000) 2>/dev/null
!kill -9 $(pgrep ngrok) 2>/dev/null

from flask import Flask, request, jsonify, render_template_string
from pyngrok import ngrok
import threading

app = Flask(__name__)

HTML_PAGE = """
<!DOCTYPE html>
<html>
<head>
  <title>RVU Smart Campus Assistant</title>
  <style>
    body { font-family: Arial, sans-serif; background: #f8f9fa; margin: 0; padding: 0; }
    .chat-box { width: 60%; margin: 40px auto; background: white; border-radius: 12px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1); padding: 20px; }
    h2 { text-align: center; color: #333; }
    #chat-area { height: 400px; overflow-y: auto; border: 1px solid #ddd;
                 border-radius: 8px; padding: 10px; margin-bottom: 10px; }
    .user { color: #0b7285; margin-bottom: 6px; }
    .bot { color: #495057; margin-bottom: 6px; }
    input[type="text"] { width: 80%; padding: 8px; }
    button { padding: 8px 12px; background: #0b7285; color: white; border: none; border-radius: 6px; }
  </style>
</head>
<body>
  <div class="chat-box">
    <h2>🤖 RVU Smart Campus Assistant</h2>
    <div id="chat-area"></div>
    <input type="text" id="user-input" placeholder="Ask something about RVU..." />
    <button onclick="sendMessage()">Send</button>
  </div>

  <script>
    async function sendMessage() {
      const input = document.getElementById("user-input");
      const chat = document.getElementById("chat-area");
      const text = input.value.trim();
      if (!text) return;

      chat.innerHTML += `<div class='user'><b>You:</b> ${text}</div>`;
      input.value = "";

      const response = await fetch("/ask", {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify({ question: text })
      });

      const data = await response.json();
      chat.innerHTML += `<div class='bot'><b>Assistant:</b> ${data.answer}</div>`;
      chat.scrollTop = chat.scrollHeight;
    }
  </script>
</body>
</html>
"""

@app.route("/")
def home():
    return render_template_string(HTML_PAGE)

@app.route("/ask", methods=["POST"])
def ask():
    try:
        user_q = request.json.get("question", "")
        if not user_q.strip():
            return jsonify({"answer": "Please ask a valid question."})

        if user_q.lower() in ["list pyq", "pyq list", "list subjects"]:
            return jsonify({"answer": list_pyq_subjects()})

        pyq_result = find_pyq_link(user_q)

        if pyq_result:
            return jsonify({"answer": pyq_result})

        response = qa_engine.query(user_q)
        answer = response.response if hasattr(response, "response") else str(response)
        return jsonify({"answer": answer})
    except Exception as e:
        return jsonify({"answer": f"Error processing RAG query: {str(e)}"})

def run_app():
    app.run(port=5000)

thread = threading.Thread(target=run_app)
thread.start()

public_url = ngrok.connect(5000).public_url
print(f"App running at: {public_url}")